### PR TITLE
Add Terraform Kubernetes documentation example

### PR DESCRIPTION
**Pull request by mcornea**
Add an example which shows how to create a simple Kubernetes pod with Protoconf and Terraform.

---
This change is [Reviewable](https://reviewable.io/reviews/protoconf/protoconf/144)

### CODE REVIEW

**Comment by smintz** [comment]
@mcornea  I just noticed a bug in the terraform importer, some messages (`Container` for example) should be marked as `repeated` but are not.
I've fixed it in #147, once I'll land this in master, can you try it and update your guide accordingly?

**Comment by mcornea** [comment]
> @mcornea I just noticed a bug in the terraform importer, some messages (`Container` for example) should be marked as `repeated` but are not.
> I've fixed it in #147, once I'll land this in master, can you try it and update your guide accordingly?

Sure, updated and tested with a build based on master(`v0.1.4-beta.0-ead23d9168753afbf6cbb0f5bb6560f17868e690`)

**Comment by mcornea** [comment]
@smintz Hey Shahar o/ is there anything else I should address in this PR? Can we merge it?

**Comment by smintz** [comment]
Nope, I'll merge, thanks!

**Pull request merged**
